import {test,expect} from '@playwright/test';
test('owner archives, restores and deletes an unused room on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/login');
  await page.getByLabel('Телефон',{exact:true}).fill('+998900000010');
  await page.getByLabel('Пароль',{exact:true}).fill('UI test only strong password 2026');
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Дом под контролем'})).toBeVisible();
  await page.getByRole('button',{name:'Добавить комнату'}).click();
  await page.getByLabel('Номер комнаты').fill('ARCHIVE-TEST');
  await page.getByLabel('Вместимость',{exact:true}).fill('2');
  await page.getByLabel('Создать мест').fill('2');
  await page.getByRole('button',{name:'Сохранить',exact:true}).click();
  await page.getByRole('heading',{name:'Комната №ARCHIVE-TEST',exact:true}).click();
  await page.getByRole('button',{name:'Убрать в архив',exact:true}).click();
  await page.getByRole('button',{name:'Подтвердить архивирование'}).click();
  await expect(page.getByText('Комната в архиве.',{exact:false})).toBeVisible();
  await expect(page.getByRole('button',{name:'Заселить',exact:true})).toHaveCount(0);
  await page.getByRole('link',{name:'Все комнаты',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Комната №ARCHIVE-TEST',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:/Архив комнат/}).click();
  await page.getByRole('heading',{name:'Комната №ARCHIVE-TEST',exact:true}).click();
  await page.getByRole('button',{name:'Восстановить комнату',exact:true}).click();
  await page.getByRole('button',{name:'Подтвердить восстановление'}).click();
  await expect(page.getByRole('button',{name:'Заселить',exact:true})).toHaveCount(2);
  await page.getByRole('button',{name:'Удалить комнату',exact:true}).click();
  await page.getByRole('button',{name:'Отмена',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Комната №ARCHIVE-TEST',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Удалить комнату',exact:true}).click();
  await page.getByLabel('Введите номер комнаты для подтверждения').fill('ARCHIVE-TEST');
  await page.getByRole('button',{name:'Удалить навсегда'}).click();
  await expect(page).toHaveURL(/\/rooms$/);
  await expect(page.getByRole('heading',{name:'Комната №ARCHIVE-TEST',exact:true})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
