-- Ijara360 / M1 / PostgreSQL schema design v0.1 / 2026-09-25
-- DESIGN ONLY. Not applied, not a production migration.
-- Mandatory service/procedure invariants are listed at the end.
-- UUIDs are generated by the application; no extension dependency.

BEGIN;

CREATE TABLE roles (
    code text PRIMARY KEY CHECK (code IN ('OWNER', 'ADMIN'))
);
INSERT INTO roles (code) VALUES ('OWNER'), ('ADMIN');

CREATE TABLE app_users (
    id uuid PRIMARY KEY,
    login varchar(64) NOT NULL UNIQUE,
    full_name varchar(160) NOT NULL CHECK (length(btrim(full_name)) > 0),
    contact_phone varchar(16),
    password_hash text NOT NULL,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    CHECK (login ~ '^[a-z0-9][a-z0-9._-]{2,63}$'),
    CHECK (contact_phone IS NULL OR contact_phone ~ '^\+[1-9][0-9]{7,14}$')
);

CREATE TABLE properties (
    id uuid PRIMARY KEY,
    name varchar(120) NOT NULL CHECK (length(btrim(name)) > 0),
    address varchar(500),
    timezone text NOT NULL DEFAULT 'Asia/Tashkent'
        CHECK (timezone = 'Asia/Tashkent'),
    currency char(3) NOT NULL DEFAULT 'UZS' CHECK (currency = 'UZS'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0)
);

CREATE TABLE property_memberships (
    property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    role_code text NOT NULL REFERENCES roles(code) ON DELETE RESTRICT,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    PRIMARY KEY (property_id, user_id)
);
CREATE INDEX membership_user_idx ON property_memberships (user_id, property_id)
    WHERE active;

CREATE TABLE rooms (
    id uuid PRIMARY KEY,
    property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
    number varchar(20) NOT NULL CHECK (length(btrim(number)) > 0),
    capacity integer NOT NULL CHECK (capacity BETWEEN 1 AND 100),
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    UNIQUE (property_id, id),
    UNIQUE (property_id, number),
    CHECK (number = upper(btrim(number)))
);
CREATE INDEX room_active_idx ON rooms (property_id, id) WHERE archived_at IS NULL;

CREATE TABLE beds (
    id uuid PRIMARY KEY,
    property_id uuid NOT NULL,
    room_id uuid NOT NULL,
    place_number varchar(20) NOT NULL CHECK (length(btrim(place_number)) > 0),
    monthly_price numeric(14,2) NOT NULL CHECK (monthly_price >= 0),
    availability_state text NOT NULL DEFAULT 'AVAILABLE'
        CHECK (availability_state IN ('AVAILABLE', 'RESERVED', 'MAINTENANCE')),
    state_note varchar(500),
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (property_id, room_id) REFERENCES rooms(property_id, id)
        ON DELETE RESTRICT,
    UNIQUE (property_id, id),
    UNIQUE (room_id, place_number),
    CHECK (place_number = upper(btrim(place_number))),
    CHECK (availability_state = 'AVAILABLE' OR
        (state_note IS NOT NULL AND length(btrim(state_note)) > 0)),
    CHECK (archived_at IS NULL OR availability_state = 'AVAILABLE')
);
CREATE INDEX bed_room_active_idx ON beds (property_id, room_id, id)
    WHERE archived_at IS NULL;
CREATE INDEX bed_state_active_idx ON beds (property_id, availability_state, id)
    WHERE archived_at IS NULL;

CREATE TABLE auth_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    csrf_hash bytea CHECK (csrf_hash IS NULL OR octet_length(csrf_hash) = 32),
    client_kind text NOT NULL CHECK (client_kind IN ('BROWSER', 'NATIVE')),
    created_at timestamptz NOT NULL DEFAULT now(),
    authenticated_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    CHECK (expires_at > created_at),
    CHECK (client_kind <> 'BROWSER' OR csrf_hash IS NOT NULL)
);
CREATE INDEX session_user_idx ON auth_sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX session_expiry_idx ON auth_sessions (expires_at);

CREATE TABLE user_invitations (
    id uuid PRIMARY KEY,
    property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
    login varchar(64) NOT NULL CHECK (login ~ '^[a-z0-9][a-z0-9._-]{2,63}$'),
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    created_by uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    accepted_by uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    revoked_at timestamptz,
    CHECK (expires_at > created_at),
    CHECK ((accepted_at IS NULL) = (accepted_by IS NULL)),
    CHECK (accepted_at IS NULL OR revoked_at IS NULL)
);
-- Expiry is checked at acceptance. Before issuing a replacement, revoke
-- a previous unaccepted/unrevoked invitation, even when it is already expired.
CREATE UNIQUE INDEX invitation_pending_login_idx ON user_invitations (login)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX invitation_property_idx ON user_invitations (property_id, created_at);

CREATE TABLE audit_logs (
    id uuid PRIMARY KEY,
    property_id uuid REFERENCES properties(id) ON DELETE RESTRICT,
    actor_user_id uuid REFERENCES app_users(id) ON DELETE RESTRICT,
    actor_kind text NOT NULL CHECK (actor_kind IN ('USER', 'SYSTEM', 'ANONYMOUS')),
    action varchar(80) NOT NULL CHECK (length(btrim(action)) > 0),
    entity_type varchar(60) NOT NULL,
    entity_id uuid,
    before_value jsonb,
    after_value jsonb,
    reason varchar(500),
    occurred_at timestamptz NOT NULL DEFAULT now(),
    request_id uuid NOT NULL,
    CHECK ((actor_kind = 'USER' AND actor_user_id IS NOT NULL)
        OR (actor_kind IN ('SYSTEM', 'ANONYMOUS') AND actor_user_id IS NULL)),
    CHECK (actor_kind <> 'SYSTEM' OR
        (reason IS NOT NULL AND length(btrim(reason)) > 0)),
    CHECK (before_value IS NULL OR jsonb_typeof(before_value) = 'object'),
    CHECK (after_value IS NULL OR jsonb_typeof(after_value) = 'object')
);
CREATE INDEX audit_property_time_idx ON audit_logs
    (property_id, occurred_at DESC, id DESC);
CREATE INDEX audit_entity_idx ON audit_logs
    (property_id, entity_type, entity_id, occurred_at DESC, id DESC);

CREATE TABLE idempotency_requests (
    actor_user_id uuid NOT NULL REFERENCES app_users(id) ON DELETE RESTRICT,
    property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
    key uuid NOT NULL,
    request_hash bytea NOT NULL CHECK (octet_length(request_hash) = 32),
    response_status integer NOT NULL CHECK (response_status BETWEEN 200 AND 299),
    response_body jsonb,
    response_etag text,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (actor_user_id, property_id, key),
    CHECK (expires_at > created_at)
);
CREATE INDEX idempotency_expiry_idx ON idempotency_requests (expires_at);

CREATE TABLE auth_rate_limits (
    bucket_hash bytea NOT NULL CHECK (octet_length(bucket_hash) = 32),
    window_started_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    attempts integer NOT NULL CHECK (attempts >= 0),
    PRIMARY KEY (bucket_hash, window_started_at),
    CHECK (expires_at > window_started_at)
);
CREATE INDEX rate_limit_expiry_idx ON auth_rate_limits (expires_at);

COMMIT;

-- REQUIRED BEFORE CONVERTING THIS DESIGN TO A PRODUCTION MIGRATION:
-- 1. Create separate migration/runtime roles and explicit GRANT/REVOKE.
--    Runtime cannot DELETE business records or UPDATE/DELETE/TRUNCATE audit.
--    Runtime inventory writes must use guarded procedures (no direct DML).
-- 2. Add guarded transaction procedures:
--    lock property -> actor membership -> room -> bed;
--    check active membership + permission, active parents, version, transitions;
--    ensure count(nonarchived beds) <= capacity on create/restore/capacity change;
--    do not archive a room with nonarchived beds; do not move a bed's room_id.
-- 3. Keep at least one active OWNER, counting only non-disabled users.
--    Lock property before membership modifications and invitation acceptance.
-- 4. Write allowlisted audit changes in the same transaction; rollback on failure.
--    Add audit UPDATE/DELETE rejection trigger in addition to privileges.
-- 5. Increment versions and updated_at on all mutations; room version also changes
--    when a bed's state/price/archive state changes. Auth sessions use no ETag.
-- 6. Serialize idempotency on an advisory transaction lock scoped to actor+key;
--    read cached response after checking current authorization, before If-Match.
--    Save successful response in the same transaction as the domain mutation.
-- 7. Implement secure bootstrap, token expiry/revocation, CSRF and rate limits.
-- 8. Integration-test against PostgreSQL, including concurrent transactions.
--
-- M2 is NOT part of this file: do not add Resident/Occupancy tables here.
-- Future public status: if active Occupancy exists then OCCUPIED,
-- else beds.availability_state. An Occupancy is the sole source of occupancy.
