'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,type Room} from '../lib/api';
import {dateLabel} from './residents';

export const applicationStatus:Record<string,string>={DRAFT:'Черновик',SUBMITTED:'Новые',UNDER_REVIEW:'На рассмотрении',NEEDS_INFO:'Требуют данных',APPROVED:'Одобрены',REJECTED:'Отклонены',CANCELLED:'Отменены',CONVERTED_TO_RESIDENT:'Заселены'};
export const permissionLabels:Record<string,string>={APPLICATION_VIEW:'Просмотр заявок',APPLICATION_REVIEW:'Рассмотрение и запрос данных',APPLICATION_APPROVE:'Одобрение заявок',APPLICATION_REJECT:'Отклонение заявок',KYC_VIEW_BASIC:'Личные данные и экстренный контакт',KYC_VIEW_DOCUMENTS:'Изображения паспорта',KYC_VIEW_PASSPORT:'ПИНФЛ и реквизиты паспорта',KYC_VIEW_BIOMETRIC_SOURCE:'Фотография лица',RESIDENT_CREATE_FROM_APPLICATION:'Заселение из заявки'};
type Item={id:string;status:string;version:number;fullName:string;phone:string;occupationType:string;organization?:string;requestedMoveInDate:string;submittedAt:string};
type Queue={items:Item[];total:number;page:number;counts:Record<string,number>;approvedToday:number};
type Detail=Item&{phoneVerified:boolean;profile:Record<string,string>;documents:{id:string;kind:string}[];duplicates:{applications:{id:string;status:string}[];resident:{id:string;fullName:string}|null};feedback:{reason:string;requiredFields?:string}|null;history:{fromStatus:string;toStatus:string;createdAt:string}[];residentId:string|null};
function useApplicationUpdates(refresh:()=>Promise<void>){
  const callback=useRef(refresh);callback.current=refresh;const [connected,setConnected]=useState(false);
  useEffect(()=>{let stopped=false;let ws:WebSocket|undefined;let timer:ReturnType<typeof setTimeout>;let delay=1000;
    const connect=()=>{ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/events`);ws.onmessage=()=>{setConnected(true);delay=1000;void callback.current();};ws.onclose=()=>{setConnected(false);if(!stopped)void callback.current();if(!stopped){timer=setTimeout(connect,delay);delay=Math.min(delay*2,15000);}};ws.onerror=()=>ws?.close();};connect();return()=>{stopped=true;clearTimeout(timer);ws?.close();};},[]);
  return connected;
}
export function ApplicationSummary(){
  const [queue,setQueue]=useState<Queue|null>(null);const [error,setError]=useState('');
  async function refresh(){try{setQueue(await api('/applications'));setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void refresh();},[]);useApplicationUpdates(refresh);
  return <section><h2>Заявки на проживание</h2>{error&&<p role="alert">{error}</p>}<div className="stats-grid">{[['SUBMITTED','Новые заявки'],['UNDER_REVIEW','На рассмотрении'],['NEEDS_INFO','Требуют данных'],['APPROVED','Одобрены сегодня']].map(([status,label])=><Link className="stat" href={`/applications?status=${status}${status==='APPROVED'?'&today=1':''}`} key={status}><span>{label}</span><strong>{status==='APPROVED'?queue?.approvedToday||0:queue?.counts[status]||0}</strong></Link>)}</div></section>;
}
export function ApplicationsPanel({id,permissions,rooms,initialStatus='SUBMITTED'}:{id?:string;permissions:string[];rooms:Room[];initialStatus?:string}){
  const router=useRouter();const [status,setStatus]=useState(initialStatus);const [page,setPage]=useState(1);const [queue,setQueue]=useState<Queue|null>(null);const [detail,setDetail]=useState<Detail|null>(null);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [fields,setFields]=useState('');const [duplicateReview,setDuplicateReview]=useState('');const [reviewed,setReviewed]=useState(false);const [document,setDocument]=useState('');const [convert,setConvert]=useState(false);
  const [rights,setRights]=useState(permissions);
  const can=(p:string)=>rights.includes(p);
  async function refresh(){try{setRights((await api<{permissions:string[]}>('/permissions/me')).permissions);if(id){const next=await api<Detail>(`/applications/${id}`);setDetail(next);
      // Realtime refreshes keep an open document unless access to it was withdrawn.
      setDocument(kind=>next.documents.some(d=>d.kind===kind)?kind:'');}else setQueue(await api(`/applications?${status==='APPROVED_TODAY'?'status=APPROVED&today=1':`status=${status}`}&page=${page}`));setError('');}catch(e){setDetail(null);setQueue(null);setDocument('');setError((e as Error).message);}}
  useEffect(()=>{void refresh();},[id,status,page]);const connected=useApplicationUpdates(refresh);
  async function action(next:string){if(!detail)return;setBusy(true);setError('');try{await api(`/applications/${detail.id}/review`,{method:'POST',body:JSON.stringify({version:detail.version,status:next,...(reason.trim()?{reason}:{}),...(fields.trim()?{requiredFields:fields}:{}),...(next==='APPROVED'?{identityReviewed:reviewed,documentsReviewed:reviewed,faceQualityConfirmed:reviewed,...(duplicateReview.trim()?{duplicateReview}:{})}:{})})});setReviewed(false);setDocument('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!can('APPLICATION_VIEW'))return <p>У вас нет доступа к заявкам.</p>;
  return <div className={id?'application-detail':''}><div className="page-heading"><div><div className="heading-kicker">ПРИЁМ ЖИЛЬЦОВ</div><h1>{id?'Карточка заявки':'Заявки'}</h1><p>{connected?'Изменения поступают автоматически':'Восстанавливаем соединение…'}</p></div></div>{error&&<div className="error" role="alert">{error}<button className="button secondary" onClick={refresh}>Обновить данные</button></div>}
    {!id?<><div className="applications-toolbar">{Object.entries(applicationStatus).filter(([s])=>s!=='DRAFT').flatMap(([s,label])=>s==='APPROVED'?[[s,label,queue?.counts[s]||0],['APPROVED_TODAY','Одобрены сегодня',queue?.approvedToday||0]]:[[s,label,queue?.counts[s]||0]]).map(([s,label,count])=><button className={`button ${status===s?'primary':'secondary'}`} key={s} onClick={()=>{setStatus(String(s));setPage(1);}}>{label} ({count})</button>)}</div><div className="application-list">{queue?.items.map(a=><Link className="application-row" href={`/applications/${a.id}`} key={a.id}><div><strong>{a.fullName}</strong><p>{a.phone} · {a.occupationType==='STUDENT'?'Студент':a.occupationType==='WORKER'?'Работает':'Другое'}</p><p>{a.organization}</p></div><div><p>Желаемое заселение: {dateLabel(a.requestedMoveInDate)}</p><small>Подана: {dateLabel(a.submittedAt)}</small></div></Link>)}</div>{queue&&!queue.items.length&&<p>Заявок с этим статусом пока нет.</p>}<div className="modal-actions"><button className="button secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Назад</button><span>Страница {page}</span><button className="button secondary" disabled={!queue||page*30>=queue.total} onClick={()=>setPage(page+1)}>Далее</button></div></>:detail&&<>
      <Link href="/applications" className="back-link">Все заявки</Link><section><h2>{detail.fullName}</h2><p>{detail.phone} · {detail.phoneVerified?'Телефон подтверждён':'Телефон не подтверждён'}</p><p className="status-pill">{applicationStatus[detail.status]}</p><dl className="application-review">{Object.entries(detail.profile).filter(([,v])=>v).map(([key,value])=><div key={key}><dt>{({occupationType:'Занятость',organization:'Учёба / работа',requestedMoveInDate:'Желаемая дата',plannedDuration:'Срок проживания',dateOfBirth:'Дата рождения',faculty:'Факультет',course:'Курс',position:'Должность',comment:'Комментарий',emergencyName:'Экстренный контакт',emergencyRelationship:'Кем приходится',emergencyPhone:'Телефон контакта',pinfl:'ПИНФЛ',passportSeries:'Серия паспорта',passportNumber:'Номер паспорта'} as Record<string,string>)[key]||key}</dt><dd>{value}</dd></div>)}</dl></section>
      {detail.documents.length>0&&<section><h2>Документы и фото</h2><div className="applications-toolbar">{detail.documents.map(d=><button key={d.id} className="button secondary" onClick={()=>setDocument(d.kind)}>{d.kind==='FACE'?'Фото лица':d.kind==='PASSPORT_FRONT'?'Паспорт: лицевая сторона':'Паспорт: обратная сторона'}</button>)}</div>{document&&<><p>Просмотр фиксируется в истории доступа.</p><img className="application-document" alt="Документ заявки" src={`/api/applications/${detail.id}/documents/${document}?v=${detail.version}`} onError={()=>{setDocument('');setError('У вас нет доступа к документу либо он временно недоступен.');}}/></>}</section>}
      {(detail.duplicates.applications.length>0||detail.duplicates.resident)&&<section><h2>Возможное совпадение</h2><p>В системе найден возможный существующий человек. Проверьте сведения перед одобрением и заселением.</p>{detail.duplicates.resident&&<p>Жилец: {detail.duplicates.resident.fullName}</p>}{detail.duplicates.applications.map(a=><p key={a.id}><Link href={`/applications/${a.id}`}>Связанная заявка: {applicationStatus[a.status]}</Link></p>)}{detail.status==='UNDER_REVIEW'&&<label>Результат проверки совпадений<textarea value={duplicateReview} maxLength={2000} onChange={e=>setDuplicateReview(e.target.value)}/></label>}</section>}
      {detail.feedback&&<section><h2>Сообщение заявителю</h2><p>{detail.feedback.reason}</p><p>{detail.feedback.requiredFields}</p></section>}
      {detail.status==='SUBMITTED'&&can('APPLICATION_REVIEW')&&<button className="button primary" disabled={busy} onClick={()=>void action('UNDER_REVIEW')}>Начать рассмотрение</button>}
      {detail.status==='UNDER_REVIEW'&&<section><h2>Решение по заявке</h2><label>Комментарий / причина<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><label>Какие данные нужны<textarea value={fields} maxLength={2000} onChange={e=>setFields(e.target.value)}/></label>{can('APPLICATION_APPROVE')&&<label><span><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> Я вручную проверил личные данные, обе стороны паспорта и качество фото лица</span></label>}<div className="applications-toolbar">{can('APPLICATION_REVIEW')&&<button className="button secondary" disabled={busy} onClick={()=>void action('NEEDS_INFO')}>Запросить данные</button>}{can('APPLICATION_REJECT')&&<button className="button secondary" disabled={busy} onClick={()=>void action('REJECTED')}>Отклонить</button>}{can('APPLICATION_APPROVE')&&<button className="button primary" disabled={busy||!reviewed} onClick={()=>void action('APPROVED')}>Одобрить</button>}</div></section>}
      {detail.status==='APPROVED'&&can('RESIDENT_CREATE_FROM_APPLICATION')&&<section><button className="button primary" onClick={()=>setConvert(!convert)}>Заселить одобренного арендатора</button>{convert&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');void api<{residentId:string}>(`/applications/${detail.id}/convert`,{method:'POST',body:JSON.stringify({version:detail.version,bedId:form.get('bedId'),moveInDate:form.get('moveInDate'),monthlyPrice:form.get('monthlyPrice'),paymentDay:Number(form.get('paymentDay')),depositAmount:form.get('depositAmount'),...(detail.duplicates.resident&&form.get('existing')?{existingResidentId:detail.duplicates.resident.id}:{})})}).then(r=>router.push(`/residents/${r.residentId}`)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Свободное место<select name="bedId" required><option value="">Выберите комнату и место</option>{rooms.filter(r=>!r.archivedAt).flatMap(r=>r.beds.filter(b=>b.status==='AVAILABLE').map(b=><option key={b.id} value={b.id}>Комната {r.number} / Место {b.number}</option>))}</select></label><label>Дата заселения<input name="moveInDate" type="date" required/></label><label>Аренда за месяц, сум<input name="monthlyPrice" inputMode="decimal" required/></label><label>День оплаты<input name="paymentDay" type="number" min={1} max={31} required defaultValue={1}/></label><label>Депозит, сум<input name="depositAmount" inputMode="decimal" required defaultValue="0"/></label>{detail.duplicates.resident&&<label><span><input type="checkbox" name="existing" required/> Использовать существующего жильца {detail.duplicates.resident.fullName}</span></label>}<button className="button primary" disabled={busy}>Подтвердить заселение</button></form>}</section>}
      {detail.residentId&&<Link className="button primary" href={`/residents/${detail.residentId}`}>Открыть жильца</Link>}
      <section><h2>История заявки</h2>{detail.history.map((h,i)=><p key={i}>{dateLabel(h.createdAt)} · {applicationStatus[h.toStatus]}</p>)}</section>
    </>}
  </div>;
}
// Role templates only pre-fill checkboxes; individual exceptions are edited before saving.
const permissionTemplates:[string,string[]][]=[
  ['Без доступа',[]],
  ['Только просмотр заявок',['APPLICATION_VIEW']],
  ['Рассмотрение без паспорта',['APPLICATION_VIEW','APPLICATION_REVIEW','APPLICATION_REJECT','KYC_VIEW_BASIC']],
  ['Полная проверка KYC',['APPLICATION_VIEW','APPLICATION_REVIEW','APPLICATION_APPROVE','APPLICATION_REJECT','KYC_VIEW_BASIC','KYC_VIEW_DOCUMENTS','KYC_VIEW_PASSPORT','KYC_VIEW_BIOMETRIC_SOURCE']],
  ['Проверка и заселение',Object.keys(permissionLabels)],
];
export function PermissionPanel(){
  const [data,setData]=useState<{available:string[];users:{id:string;fullName:string;permissions:string[];protected:boolean}[]}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<typeof data>('/permissions/staff').then(setData).catch(e=>setError(e.message));},[]);
  return <section className="settings-card"><h2>Права на заявки и документы</h2>{error&&<p className="error" role="alert">{error}</p>}{data?.users.map(user=><form key={user.id} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');void api(`/permissions/users/${user.id}`,{method:'PUT',body:JSON.stringify({permissions:form.getAll('permissions')})}).then(()=>api<typeof data>('/permissions/staff')).then(setData).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><h3>{user.fullName}</h3>{user.protected?<p>Владелец / SUPER_ADMIN: все права, ограничение недоступно.</p>:<><div className="applications-toolbar" aria-label="Шаблоны прав">{permissionTemplates.map(([name,codes])=><button type="button" className="button secondary" key={name} disabled={busy} onClick={e=>{e.currentTarget.form?.querySelectorAll<HTMLInputElement>('input[name=permissions]').forEach(input=>{input.checked=codes.includes(input.value);});}}>{name}</button>)}</div><p className="form-hint">Шаблон заполняет отметки; отдельные права можно изменить перед сохранением.</p><div className="permission-grid" key={user.permissions.join(',')}>{data.available.map(p=><label key={p}><input type="checkbox" name="permissions" value={p} defaultChecked={user.permissions.includes(p)} disabled={busy}/>{permissionLabels[p]}</label>)}</div><button className="button secondary" disabled={busy}>Сохранить права</button></>}</form>)}</section>;
}
