'use client';
import {useEffect,useRef,useState} from 'react';
import {api,ApiError} from '../lib/api';

const statuses:Record<string,string>={DRAFT:'Черновик',SUBMITTED:'Заявка принята',UNDER_REVIEW:'На рассмотрении',NEEDS_INFO:'Нужна дополнительная информация',APPROVED:'Одобрено',REJECTED:'Отклонено',CANCELLED:'Заявка отменена',CONVERTED_TO_RESIDENT:'Вы заселены'};
const steps=['Телефон','Личные данные','Учёба / работа','Проживание','Экстренный контакт','Фото паспорта','Фото лица','Проверка и отправка'];
type Profile=Record<string,string|boolean>;
type Draft={id:string;status:string;version:number;profile:Profile;phoneVerified:boolean;documents:{id:string;kind:string}[];feedback:{reason:string;requiredFields?:string}|null};
export default function Apply(){
  const [config,setConfig]=useState<{enabled:boolean;propertyName:string;phoneProvider:string}|null>(null);
  const [app,setApp]=useState<Draft|null>(null);const [profile,setProfile]=useState<Profile>({});
  const [phone,setPhone]=useState('');const [step,setStep]=useState(0);const [loaded,setLoaded]=useState(false);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState('');const [verifyUrl,setVerifyUrl]=useState('');
  const current=useRef<Draft|null>(null);const fields=useRef<Profile>({});const revision=useRef(0);const stored=useRef(0);const saving=useRef<Promise<void>|null>(null);
  const editable=app&&['DRAFT','NEEDS_INFO'].includes(app.status);
  function install(a:Draft){current.current=a;setApp(a);fields.current=a.profile;setProfile(a.profile);revision.current=0;stored.current=0;}
  async function load(){const a=await api<Draft>('/public/applications/me');install(a);return a;}
  // A resumed draft with a verified phone continues from personal data.
  useEffect(()=>{void(async()=>{try{setConfig(await api('/public/applications/config'));try{const a=await load();if(a.phoneVerified)setStep(1);}catch(e){if(!(e instanceof ApiError&&e.status===401))throw e;}}catch(e){setError((e as Error).message);}finally{setLoaded(true);}})();},[]);
  function change(key:string,value:string|boolean){fields.current={...fields.current,[key]:value};revision.current++;setProfile(fields.current);setSaved('Есть несохранённые изменения');}
  async function persist(){
    if(saving.current)await saving.current;
    if(!current.current||stored.current===revision.current)return;
    const rev=revision.current;const {phone:_,...data}=fields.current;
    const job=(async()=>{const next=await api<Draft>('/public/applications/me',{method:'PATCH',body:JSON.stringify({...data,version:current.current!.version})});current.current=next;setApp(next);stored.current=rev;setSaved(stored.current===revision.current?'Черновик сохранён на сервере':'Есть несохранённые изменения');})();
    saving.current=job;try{await job;}finally{if(saving.current===job)saving.current=null;}
  }
  useEffect(()=>{if(!editable||busy)return;const timer=setTimeout(()=>{void persist().catch(e=>setError(e.message));},900);return()=>clearTimeout(timer);},[profile,editable,busy]);
  useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(stored.current!==revision.current){e.preventDefault();}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[]);
  useEffect(()=>{if(!app||editable&&!verifyUrl)return;let disposed=false;const timer=setInterval(()=>{if(busy||saving.current||stored.current!==revision.current)return;void api<Draft>('/public/applications/me').then(a=>{if(!disposed){install(a);if(a.phoneVerified)setVerifyUrl('');}}).catch(()=>{});},4000);return()=>{disposed=true;clearInterval(timer);};},[app?.id,editable,verifyUrl,busy]);
  async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function input(key:string,label:string,type='text',maxLength=160){return <label>{label}<input type={type} maxLength={maxLength} value={String(profile[key]||'')} onChange={e=>change(key,e.target.value)} disabled={busy}/></label>;}
  async function upload(kind:string,file:File|undefined){if(!file)return;await work(async()=>{await persist();if(file.size>8*1024*1024)throw Error('Максимальный размер — 8 МБ.');const response=await fetch(`/api/public/applications/documents/${kind}`,{method:'PUT',headers:{'Content-Type':file.type,'X-Ijara-Request':'1'},body:file,credentials:'same-origin'});if(!response.ok){const d=await response.json();throw Error(d.message||'Не удалось загрузить документ.');}await load();});}
  function file(kind:string,label:string){const doc=app?.documents.find(d=>d.kind===kind);return <section className="application-file"><label>{label}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!app?.phoneVerified} onChange={e=>void upload(kind,e.target.files?.[0])}/></label>{doc&&<><p>Загружено</p><img alt={label} src={`/api/public/applications/documents/${kind}?v=${app?.version}`}/></>}</section>;}
  return <main className="apply-shell"><header><a className="apply-brand" href="/apply">ijara360</a><span>{config?.propertyName||'Анкета арендатора'}</span></header><section className="apply-card">
    <h1>Заявка на проживание</h1>{error&&<div className="error" role="alert">{error}</div>}
    {!loaded?<p>Загружаем анкету…</p>:!app?<><p>Заполните анкету и отправьте документы администрации. Заселение оформляется после рассмотрения.</p>{!config?.enabled?<p>Приём заявок пока не настроен. Обратитесь к администрации.</p>:<form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/public/applications',{method:'POST',body:JSON.stringify({phone,channel:new URLSearchParams(window.location.search).get('channel')==='TELEGRAM'?'TELEGRAM':'WEB'})});await load();});}}><label>Ваш телефон<input type="tel" required value={phone} maxLength={30} onChange={e=>setPhone(e.target.value)} placeholder="+998 90 123 45 67"/></label><p className="form-hint">Используйте номер, привязанный к вашему Telegram. Черновик будет доступен в этом браузере 30 дней.</p><button className="button primary" disabled={busy}>Начать анкету</button></form>}</>:<>
      <p className="status-pill">{statuses[app.status]}</p>
      {app.feedback&&<aside className="application-feedback"><strong>Комментарий администрации</strong><p>{app.feedback.reason}</p>{app.feedback.requiredFields&&<p>Нужно дополнить: {app.feedback.requiredFields}</p>}</aside>}
      {!editable?<><p>{['APPROVED','CONVERTED_TO_RESIDENT'].includes(app.status)?'Ваша заявка одобрена. После заселения вам будет предоставлен доступ к приложению арендатора.':'Статус обновляется автоматически. Сохраните доступ к этому браузеру.'}</p>{['SUBMITTED','UNDER_REVIEW'].includes(app.status)&&<button className="button secondary" disabled={busy} onClick={()=>void work(async()=>{install(await api('/public/applications/cancel',{method:'POST',body:JSON.stringify({version:app.version})}));})}>Отозвать заявку</button>}</>:<>
        <p className="form-hint">Шаг {step+1} из {steps.length}</p><h2>{steps[step]}</h2>
        <fieldset disabled={busy}>
        {step===0&&<><p>Телефон: {String(profile.phone||'')}</p><p>{app.phoneVerified?'Телефон подтверждён':'Телефон пока не подтверждён'}</p>{!app.phoneVerified&&<><button className="button secondary" type="button" onClick={()=>void work(async()=>{await persist();const r=await api<{url:string}>('/public/applications/phone',{method:'POST'});setVerifyUrl(r.url);})}>Подтвердить через Telegram</button>{verifyUrl&&<a className="button primary" href={verifyUrl} target="_blank" rel="noreferrer">Открыть бота и передать свой контакт</a>}{config?.phoneProvider==='NOT_CONFIGURED'&&<p>Подтверждение телефона ещё не подключено.</p>}</>}</>}
        {step===1&&<>{input('fullName','ФИО')}{input('dateOfBirth','Дата рождения','date',10)}{input('pinfl','ПИНФЛ — 14 цифр','text',14)}{input('passportSeries','Серия паспорта — 2 латинские буквы','text',2)}{input('passportNumber','Номер паспорта — 7 цифр','text',7)}<p className="form-hint">Паспортные сведения доступны только сотрудникам с отдельным правом просмотра паспорта.</p></>}
        {step===2&&<><label>Занятость<select value={String(profile.occupationType||'')} onChange={e=>change('occupationType',e.target.value)}><option value="">Выберите</option><option value="STUDENT">Студент</option><option value="WORKER">Работаю</option><option value="OTHER">Другое</option></select></label>{profile.occupationType!=='OTHER'&&input('organization',profile.occupationType==='STUDENT'?'Университет / институт':'Место работы','text',200)}{profile.occupationType==='STUDENT'&&<>{input('faculty','Факультет (необязательно)')}{input('course','Курс (необязательно)','text',2)}</>}{profile.occupationType==='WORKER'&&input('position','Должность (необязательно)')}</>}
        {step===3&&<>{input('requestedMoveInDate','Желаемая дата заселения','date',10)}{input('plannedDuration','Планируемый срок проживания','text',120)}<label>Комментарий (необязательно)<textarea value={String(profile.comment||'')} maxLength={2000} onChange={e=>change('comment',e.target.value)}/></label></>}
        {step===4&&<>{input('emergencyName','ФИО контактного лица')}{input('emergencyRelationship','Кем приходится','text',80)}{input('emergencyPhone','Телефон контактного лица','tel',30)}</>}
        {step===5&&<><p>Загрузите чёткие изображения без бликов, все края документа должны быть видны. JPG, PNG или WebP, до 8 МБ.</p>{!app.phoneVerified&&<p>Для загрузки сначала подтвердите телефон на шаге «Телефон».</p>}{file('PASSPORT_FRONT','Передняя сторона паспорта')}{file('PASSPORT_BACK','Обратная сторона паспорта')}</>}
        {step===6&&<><p>Один человек в кадре, лицо крупным планом, взгляд в камеру, ровный свет, без маски и солнцезащитных очков. Минимум 480 × 480 пикселей.</p><p className="form-hint">Фото проверит сотрудник. Автоматическое распознавание лица сейчас не выполняется.</p>{file('FACE','Фотография лица')}</>}
        {step===7&&<><dl className="application-review">{Object.entries(profile).filter(([key])=>key!=='consent').map(([key,value])=><div key={key}><dt>{({fullName:'ФИО',phone:'Телефон',dateOfBirth:'Дата рождения',pinfl:'ПИНФЛ',passportSeries:'Серия паспорта',passportNumber:'Номер паспорта',occupationType:'Занятость',organization:'Учёба / работа',faculty:'Факультет',course:'Курс',position:'Должность',emergencyName:'Контактное лицо',emergencyRelationship:'Кем приходится',emergencyPhone:'Телефон контакта',requestedMoveInDate:'Дата заселения',plannedDuration:'Срок',comment:'Комментарий'} as Record<string,string>)[key]||key}</dt><dd>{String(value)}</dd></div>)}</dl><p>Загружено документов: {app.documents.length} из 3</p><label className="application-consent"><input type="checkbox" checked={Boolean(profile.consent)} onChange={e=>change('consent',e.target.checked)}/>Я согласен на обработку анкеты, паспортных изображений, контактных данных и фотографии лица администрацией для рассмотрения заявки. Фото лица сохраняется как исходник для будущего подключения биометрического доступа; сейчас распознавание не выполняется.</label></>}
        </fieldset>
        <div className="modal-actions"><button className="button secondary" disabled={busy||step===0} onClick={()=>void work(async()=>{await persist();setStep(step-1);})}>Назад</button>{step<7?<button className="button primary" disabled={busy} onClick={()=>void work(async()=>{await persist();setStep(step+1);})}>Далее</button>:<button className="button primary" disabled={busy||!app.phoneVerified} onClick={()=>void work(async()=>{await persist();install(await api('/public/applications/submit',{method:'POST',body:JSON.stringify({version:current.current!.version})}));})}>Отправить заявку</button>}</div><p role="status" className="form-hint">{saved}</p>
      </>}
    </>}
  </section><footer>Документы хранятся в закрытом хранилище. Не отправляйте паспорт или фото лица в чат Telegram.</footer></main>;
}
